import { useState } from 'react';
import './App.css';
import UploadForm from './components/UploadForm';
import ModeSelector from './components/ModeSelector';
import SummaryView from './components/SummaryView';
import QueryInput from './components/QueryInput';
import Loader from './components/Loader';

function App() {
  const [file, setFile] = useState<File | null>(null);
  const [mode, setMode] = useState('balanced');
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const [isQuerying, setIsQuerying] = useState(false);

  const handleFileSelect = (selectedFile: File) => {
    setFile(selectedFile);
    // Auto-start summarization mock
    startSummarization(selectedFile);
  };

  const startSummarization = (selectedFile: File) => {
    setIsSummarizing(true);
    setSummary(null);

    // Mock API call
    setTimeout(() => {
      setIsSummarizing(false);
      setSummary(`Summary of ${selectedFile.name}:\n\nThis is a mocked summary to demonstrate the glassmorphism UI. In a real integration, the backend would process the document and return a structured analysis here.\n\nKey points would include:\n- Intelligent Chunking\n- Contextual Analysis\n- Semantic Preservation`);
    }, 2500);
  };

  const handleQuery = (query: string) => {
    setIsQuerying(true);
    // Mock Query Response
    setTimeout(() => {
      setIsQuerying(false);
      setSummary(prev => `${prev}\n\n**Q&A Response for "${query}":**\nBased on the document content, this is how I would answer your specific question. The response is generated by analyzing relevant chunks of text.`);
    }, 1500);
  };

  const resetAll = () => {
    setFile(null);
    setSummary(null);
    setMode('balanced');
  };

  return (
    <div className="main-container">
      <div className="glow"></div>
      <div className="glow glow-2"></div>

      <header className="hero-section">
        <h1 className="hero-title">Smart Summarizer</h1>
        <p className="hero-subtitle">Transform long documents into concise, actionable insights using AI.</p>
      </header>

      {!file && !isSummarizing && (
        <UploadForm onFileSelect={handleFileSelect} />
      )}

      {file && (
        <div className="flex flex-col items-center gap-8 w-full max-w-4xl">
          {!summary && !isSummarizing ? (
            <div className="glass-card p-6 flex items-center gap-4">
              <span className="text-zinc-400">File: {file.name}</span>
              <button onClick={resetAll} className="text-xs text-red-400 hover:text-red-300">Remove</button>
            </div>
          ) : null}

          {isSummarizing ? (
            <Loader />
          ) : (
            <>
              {summary && (
                <>
                  <ModeSelector currentMode={mode} onModeChange={(m) => { setMode(m); startSummarization(file); }} />
                  <SummaryView summary={summary} onReset={resetAll} />
                  <QueryInput onQuery={handleQuery} isPending={isQuerying} />
                </>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}

export default App;